---
engines:
  phpcs:
    php_version: 5.5
  duplication:
    minTokenMatch: 20
    skipLexicalErrors: false
    ignoreLiterals: false
    ignoreIdentifiers: false
    ignoreAnnotations: false
    ignoreUsings: false